export const useLang = () => "th" as const;
export const T = {
  th: {
    tagline:"หาเพื่อนเล่นกีฬา มก.", university:"มหาวิทยาลัยเกษตรศาสตร์",
    login:"เข้าสู่ระบบ", register:"สมัครสมาชิก",
    ph_firstname:"ชื่อ", ph_lastname:"นามสกุล", ph_nickname:"ชื่อเล่น",
    ph_dob:"วันเดือนปีเกิด", ph_email:"Email @ku.th",
    ph_password:"รหัสผ่าน (อย่างน้อย 6 ตัว)", ph_confirm_pw:"ยืนยันรหัสผ่าน",
    err_email:"กรุณาใช้ Email @ku.th เท่านั้น",
    err_pw_short:"รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร",
    err_pw_match:"รหัสผ่านไม่ตรงกัน กรุณาตรวจสอบอีกครั้ง",
    ku_only:"ระบบนี้ใช้งานได้เฉพาะนิสิต มก. ที่มี Email @ku.th เท่านั้น",
    nav_swipe:"ปัด", nav_sessions:"ห้องทั่วไป", nav_chat:"แชท", nav_events:"กิจกรรม", nav_profile:"โปรไฟล์",
    nav_notifs:"แจ้งเตือน", nav_search:"ค้นหา", nav_settings:"ตั้งค่า",
    save:"บันทึก", cancel:"ยกเลิก", delete:"ลบ", create:"สร้าง", edit:"แก้ไข",
    back:"กลับ", close:"ปิด", reset:"รีเซ็ต", send:"ส่ง", skip:"ข้าม",
    all:"ทั้งหมด", next:"ถัดไป", done:"เสร็จสิ้น", add:"เพิ่ม",
    upcoming:"กำลังจะมาถึง", past:"จัดไปแล้ว",
    swipe_filter:"กรองคู่ปัด", apply_filter:"ใช้ตัวกรอง",
    sport:"กีฬา", level_label:"ระดับ", avail_day:"วันที่ว่าง",
    sessions_title:"ห้องทั่วไป", create_session:"สร้างห้องทั่วไป",
    back_sessions:"กลับห้องทั่วไป", room_name:"ชื่อห้อง",
    room_ph:"เช่น แบด 2v2 บ่ายนี้", max_players:"จำนวนสูงสุด",
    join:"เข้าร่วม", leave:"ออก", kick:"เตะออก", disband:"ยุบ",
    type_msg:"พิมพ์ข้อความ...", chat_title:"แชท",
    events_title:"กิจกรรม", filter_events:"กรองกิจกรรม",
    edit_profile:"แก้ไขโปรไฟล์", save_success:"บันทึกสำเร็จ!", saved_title:"บันทึกแล้ว!",
    back_profile:"กลับโปรไฟล์",
    settings_title:"ตั้งค่า", language:"ภาษา", lang_th:"ไทย", lang_en:"English",
    admin_panel:"Admin Panel", back_app:"กลับแอป",
    organizer_title:"ผู้จัดกิจกรรม", my_events:"กิจกรรมของฉัน",
    date:"วันที่", time_start:"เวลาเริ่ม", time_end:"เวลาสิ้นสุด",
    venue:"สนาม", equipment:"มีอุปกรณ์กีฬา",
    equip_desc:"แสดงบนปัดการ์ดและห้องทั่วไป",
    equip_desc2:"ระบุว่าคุณมีอุปกรณ์หรือไม่",
    search_ph:"ค้นหาห้อง, กิจกรรม, ผู้ใช้...",
    no_results:"ไม่พบผลลัพธ์", notifs_title:"แจ้งเตือน",
    report_title:"รายงาน", qr_title:"QR Check-in",
    block:"บล็อก", unblock:"ยกเลิกบล็อก", blocked:"บล็อกแล้ว",
    report:"รายงาน", share:"แชร์", chat_btn:"แชท",
    session_created:"สร้างห้องแล้ว!", back_room:"กลับห้องทั่วไป",
    favorites:"สนามประจำ", available_days:"วันที่ว่าง", avail_time:"ช่วงเวลาว่าง",
    sports_played:"กีฬาที่เล่น", skill_level:"ระดับฝีมือ",
    start:"เริ่ม", end:"สิ้นสุด", add_venue:"+ เพิ่มสนาม",
    main_photo:"หลัก", add_photo:"เพิ่มรูป",
    profile_photos:"รูปโปรไฟล์", photo_hint:"(สูงสุด 5 รูป · รูปแรกเป็นรูปหลัก)",
    notify_match:"แจ้งเตือน Match", notify_chat:"แจ้งเตือนแชท",
    change_pw:"เปลี่ยนรหัสผ่าน", blocked_list:"รายชื่อที่บล็อก",
    sent_reports:"Report ที่ส่ง", logout:"ออกจากระบบ",
    logout_all:"ออกจากระบบทุกอุปกรณ์", logout_this:"ออกจากระบบ (เครื่องนี้)",
    my_devices:"อุปกรณ์ที่ใช้งาน", security:"ความปลอดภัย",
    notifications:"การแจ้งเตือน", account:"บัญชีและความเป็นส่วนตัว", tools:"เครื่องมือ",
    onboard_sport_title:"เลือกกีฬา", onboard_sport_sub:"เลือกอย่างน้อย 1 กีฬา",
    onboard_level_title:"ระดับฝีมือ", onboard_level_sub:"ใช้จับคู่ให้เหมาะสม",
    onboard_time_title:"ช่วงเวลาว่าง", onboard_time_sub:"ระบบนำไปใช้จับคู่ Match",
    onboard_venue_title:"สนามประจำ", onboard_venue_sub:"เลือกได้สูงสุด 5 สนาม",
    onboard_photo_title:"รูปโปรไฟล์", onboard_photo_sub:"เพิ่มรูปเพื่อให้คนอื่นรู้จักคุณ",
    search_venue:"ค้นหาสนาม...",
    session_room:"ห้องทั่วไป ({n})",
    create_event:"สร้างกิจกรรม", create_event_new:"สร้างกิจกรรมใหม่",
    event_name:"ชื่อกิจกรรม",
    manage:"จัดการ", stats:"สถิติ", members:"สมาชิก", announce:"ประกาศ",
    qr_scan:"สแกน QR",
    send_announce:"ส่งประกาศ", announce_title_ph:"หัวข้อประกาศ",
    announce_body_ph:"รายละเอียดประกาศ...",
    no_announce:"ยังไม่มีประกาศ",
    sent_announce:"ประกาศที่ส่งแล้ว",
    checkin:"Check-in", not_arrived:"ยังไม่มา",
    rate:"อัตรา", applicants:"ผู้สมัคร", event_date:"วันจัดงาน",
    export:"Export",
    invite:"ส่ง Invite", invite_title:"🏸 ส่ง Sport Invite",
    invite_ph:"ข้อความเชิญ (ไม่บังคับ)",
    invite_count:"จำนวนคน",
    unsent:"เลิกส่งแล้ว",
    verified_badge:"Verified KU Student",
    match_stat:"Match", room_stat:"ห้อง", badge_stat:"Badge",
    filter_sport:"กีฬา: ทั้งหมด",
    sessions_empty:"ไม่พบห้องที่ตรงเงื่อนไข",
    session_detail:"รายละเอียด →",
    join_btn:"เข้าร่วม Session",
    leave_btn:"ออกจาก Session",
    disband_btn:"ยุบ Session",
    no_notifs:"ไม่มีการแจ้งเตือน",
    mark_all_read:"อ่านทั้งหมด",
    search_results:"ผลลัพธ์",
    room_results:"ห้องทั่วไป",
    event_results:"กิจกรรม",
    search_filter_label:"กรอง",
    filter:"กรอง",
    language_label:"ภาษา",
    notif_settings:"การแจ้งเตือน",
    notif_match:"แจ้งเตือน Match",
    notif_match_sub:"เมื่อมีคนชอบคุณ",
    notif_session:"แจ้งเตือนห้องทั่วไป",
    notif_session_sub:"มีคนเข้าร่วมหรือส่งข้อความ",
    notif_event:"แจ้งเตือนกิจกรรม",
    notif_event_sub:"กิจกรรมใหม่และอัปเดต",
    privacy_label:"ความเป็นส่วนตัว",
    privacy_policy:"นโยบายความเป็นส่วนตัว",
    terms:"ข้อกำหนดการใช้งาน",
    report_sent:"ส่งรายงานแล้ว!",
    report_sent_sub:"ทีมงานจะตรวจสอบภายใน 24-48 ชั่วโมง",
    report_reason:"เหตุผลในการรายงาน",
    report_detail:"รายละเอียดเพิ่มเติม",
    report_detail_ph:"อธิบายสิ่งที่เกิดขึ้น...",
    submit_report:"ส่งรายงาน",
    optional:"ไม่บังคับ",
    filter_label:"ตัวกรอง",
    suggestions:"แนะนำ",
    organizer_panel:"ผู้จัดกิจกรรม",
    search_event_ph:"ค้นหากิจกรรม...",
    search_session_ph:"ค้นหาห้อง...",
    avail_period:"ช่วงเวลา",
    selected:"เลือกแล้ว",
    avail_day_label:"วันที่ว่าง",
  },
  en: {
    tagline:"Find Sports Partners at KU", university:"Kasetsart University",
    login:"Login", register:"Register",
    ph_firstname:"First Name", ph_lastname:"Last Name", ph_nickname:"Nickname",
    ph_dob:"Date of Birth", ph_email:"Email @ku.th",
    ph_password:"Password (min 6 chars)", ph_confirm_pw:"Confirm Password",
    err_email:"Please use @ku.th email only",
    err_pw_short:"Password must be at least 6 characters",
    err_pw_match:"Passwords do not match",
    ku_only:"This system is for KU students with @ku.th email only",
    nav_swipe:"Swipe", nav_sessions:"Rooms", nav_chat:"Chat", nav_events:"Events", nav_profile:"Profile",
    nav_notifs:"Notifications", nav_search:"Search", nav_settings:"Settings",
    save:"Save", cancel:"Cancel", delete:"Delete", create:"Create", edit:"Edit",
    back:"Back", close:"Close", reset:"Reset", send:"Send", skip:"Skip",
    all:"All", next:"Next", done:"Done", add:"Add",
    upcoming:"Upcoming", past:"Past",
    swipe_filter:"Filter Swipe", apply_filter:"Apply Filter",
    sport:"Sport", level_label:"Level", avail_day:"Available Day",
    sessions_title:"Rooms", create_session:"Create Room",
    back_sessions:"Back to Rooms", room_name:"Room Name",
    room_ph:"e.g. Badminton 2v2 tonight", max_players:"Max Players",
    join:"Join", leave:"Leave", kick:"Kick", disband:"Disband",
    type_msg:"Type a message...", chat_title:"Chat",
    events_title:"Events", filter_events:"Filter Events",
    edit_profile:"Edit Profile", save_success:"Saved!", saved_title:"Saved!",
    back_profile:"Back to Profile",
    settings_title:"Settings", language:"Language", lang_th:"ไทย", lang_en:"English",
    admin_panel:"Admin Panel", back_app:"Back to App",
    organizer_title:"Event Organizer", my_events:"My Events",
    date:"Date", time_start:"Start Time", time_end:"End Time",
    venue:"Venue", equipment:"Has Equipment",
    equip_desc:"Shown on swipe cards and rooms",
    equip_desc2:"Specify if you have equipment",
    search_ph:"Search rooms, events, users...",
    no_results:"No results found", notifs_title:"Notifications",
    report_title:"Report", qr_title:"QR Check-in",
    block:"Block", unblock:"Unblock", blocked:"Blocked",
    report:"Report", share:"Share", chat_btn:"Chat",
    session_created:"Room Created!", back_room:"Back to Rooms",
    favorites:"Favorite Venues", available_days:"Available Days", avail_time:"Available Hours",
    sports_played:"Sports Played", skill_level:"Skill Level",
    start:"Start", end:"End", add_venue:"+ Add Venue",
    main_photo:"Main", add_photo:"Add Photo",
    profile_photos:"Profile Photos", photo_hint:"(max 5 · first photo is main)",
    notify_match:"Match Notifications", notify_chat:"Chat Notifications",
    change_pw:"Change Password", blocked_list:"Blocked Users",
    sent_reports:"Sent Reports", logout:"Log Out",
    logout_all:"Log Out All Devices", logout_this:"Log Out (This Device)",
    my_devices:"Active Devices", security:"Security",
    notifications:"Notifications", account:"Account & Privacy", tools:"Tools",
    onboard_sport_title:"Choose Sports", onboard_sport_sub:"Choose at least 1 sport",
    onboard_level_title:"Skill Level", onboard_level_sub:"Used for matchmaking",
    onboard_time_title:"Available Hours", onboard_time_sub:"Used to find your match",
    onboard_venue_title:"Favorite Venues", onboard_venue_sub:"Choose up to 5 venues",
    onboard_photo_title:"Profile Photo", onboard_photo_sub:"Add a photo so others can find you",
    search_venue:"Search venue...",
    session_room:"Room ({n})",
    create_event:"Create Event", create_event_new:"Create New Event",
    event_name:"Event Name",
    manage:"Manage", stats:"Stats", members:"Members", announce:"Announce",
    qr_scan:"Scan QR",
    send_announce:"Send Announcement", announce_title_ph:"Announcement Title",
    announce_body_ph:"Announcement details...",
    no_announce:"No announcements yet",
    sent_announce:"Sent Announcements",
    checkin:"Check-in", not_arrived:"Not Arrived",
    rate:"Rate", applicants:"Applicants", event_date:"Event Date",
    export:"Export",
    invite:"Send Invite", invite_title:"🏸 Sport Invite",
    invite_ph:"Invite message (optional)",
    invite_count:"Players",
    unsent:"Unsent",
    verified_badge:"Verified KU Student",
    match_stat:"Match", room_stat:"Rooms", badge_stat:"Badge",
    filter_sport:"Sport: All",
    sessions_empty:"No rooms found",
    session_detail:"Details →",
    join_btn:"Join Session",
    leave_btn:"Leave Session",
    disband_btn:"Disband Session",
    no_notifs:"No notifications",
    mark_all_read:"Mark all read",
    search_results:"Results",
    room_results:"Rooms",
    event_results:"Events",
    search_filter_label:"Filter",
    filter:"Filter",
    language_label:"Language",
    notif_settings:"Notifications",
    notif_match:"Match Notifications",
    notif_match_sub:"When someone likes you",
    notif_session:"Room Notifications",
    notif_session_sub:"Someone joined or sent a message",
    notif_event:"Event Notifications",
    notif_event_sub:"New events and updates",
    privacy_label:"Privacy",
    privacy_policy:"Privacy Policy",
    terms:"Terms of Service",
    report_sent:"Report Submitted!",
    report_sent_sub:"Our team will review within 24-48 hours",
    report_reason:"Reason for Report",
    report_detail:"Additional Details",
    report_detail_ph:"Describe what happened...",
    submit_report:"Submit Report",
    optional:"optional",
    filter_label:"Filters",
    suggestions:"Suggestions",
    organizer_panel:"Event Organizer",
    search_event_ph:"Search events...",
    search_session_ph:"Search rooms...",
    avail_period:"Time Range",
    selected:"Selected",
    avail_day_label:"Available Days",
  }
} as const;
